# Collector specific configuration

source_dataset: "unhcr-population-data-for-world"

source_resource: "Demographics and locations of forcibly displaced and stateless people (Global)"

output_datasets:
  refugees:
    name: "hdx-hapi-refugees"
    title: "HDX HAPI - Affected People: Refugees & Persons of Concern"
  returnees:
    name: "hdx-hapi-returnees"
    title: "HDX HAPI - Affected People: Returnees"

resources:
  refugees:
    name: "Global Affected People: Refugees & Persons of Concern (YYYY)"
    description: "Refugees and Persons of Concern data (YYYY) from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#refugees-persons-of-concern) for more information"
  returnees:
    name: "Global Affected People: Returnees"
    description: "Returnees data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#returnees) for more information"

tags:
  refugees:
    - "refugees"
  returnees:
    - "returnees"

headers:
  - origin_location_code
  - origin_has_hrp
  - origin_in_gho
  - asylum_location_code
  - asylum_has_hrp
  - asylum_in_gho
  - population_group
  - gender
  - age_range
  - min_age
  - max_age
  - population
  - reference_period_start
  - reference_period_end
  - dataset_hdx_id
  - resource_hdx_id
  - warning
  - error
