# Collector specific configuration

source_dataset: "unhcr-population-data-for-world"

source_resource: "Demographics and locations of forcibly displaced and stateless persons (Global)"

output_datasets:
  refugees:
    name: "hdx-hapi-refugees"
    title: "HDX HAPI - Affected People: Refugees & Persons of Concern"
  returnees:
    name: "hdx-hapi-returnees"
    title: "HDX HAPI - Affected People: Returnees"

resources:
  refugees:
    name: "Global Affected People: Refugees & Persons of Concern"
    description: "Refugees and Persons of Concern data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#refugees-persons-of-concern) for more information"
  returnees:
    name: "Global Affected People: Returnees"
    description: "Returnees data from HDX HAPI, please see [the documentation](https://hdx-hapi.readthedocs.io/en/latest/data_usage_guides/affected_people/#returnees) for more information"

tags:
  refugees:
    - "refugees"
  returnees:
    - "returnees"

hxl_tags:
  origin_location_code: "#country+code+origin"
  origin_has_hrp: "#meta+has_hrp+origin"
  origin_in_gho: "#meta+in_gho+origin"
  asylum_location_code: "#country+code+asylum"
  asylum_has_hrp: "#meta+has_hrp+asylum"
  asylum_in_gho: "#meta+in_gho+asylum"
  population_group: "#population_group+code"
  gender: "#gender+code"
  age_range: "#age+range"
  min_age: "#age+min"
  max_age: "#age+max"
  population: "#population"
  reference_period_start: "#date+start"
  reference_period_end: "#date+end"
  dataset_hdx_id: "#meta+dataset_id"
  resource_hdx_id: "#meta+resource_id"
  warning: "#meta+warning"
  error: "#meta+error"
